//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.21 at 12:03:53 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kir.ru/soap/backend/users", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.kir.soap.backend.generated_data.users;
